amqp_port: 443
display_name: ESGF-CROCUS
engine:
  provider:
    init_blocks: 1
    max_blocks: 1
    min_blocks: 0
    type: LocalProvider
    worker_init: |
      . "/home/bcote/anaconda3/etc/profile.d/conda.sh"
      conda activate ingests-dev
  type: GlobusComputeEngine
allowed_functions:
  - ... # Add your function UUID here
