amqp_port: 443
display_name: ESGF-CROCUS-Local
engine:
  max_workers_per_node: 1
  provider:
    init_blocks: 1
    max_blocks: 1
    min_blocks: 0
    type: LocalProvider
    worker_init: |
      conda activate esgf-crocus
  type: GlobusComputeEngine
allowed_functions:
  - 1c4aea51-52a0-4235-a5d2-cff872abc001
  - b4930dc7-6c35-4cdc-910d-82765073b706
