amqp_port: 443
display_name: ESGF-CROCUS-Local
engine:
  max_workers_per_node: 1
  provider:
    init_blocks: 1
    max_blocks: 1
    min_blocks: 0
    type: LocalProvider
    worker_init: |
      conda activate esgf-crocus
  type: GlobusComputeEngine
allowed_functions:
  - 166e572b-bbd0-4590-bb71-abad9503426a
